openapi: 3.0.3
info:
    title: Argent Bank API
    version: 1.0.0
    description: Argent Bank Accounts and transactions API (phase 2)

servers:
    - url: https://api.argentbank.local
      description: Main instance

paths:
    /accounts:
        get:
            summary: List user's accounts
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: Accounts retrieved
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Account'
                '401':
                    description: Invalid or expired token
                '404':
                    description: No accounts found
                '500':
                    description: Server error

    /accounts/{accountId}/transactions:
        get:
            summary: List transactions
            security:
                - bearerAuth: []
            parameters:
                - name: accountId
                  in: path
                  required: true
                  schema:
                      type: string
                - name: month
                  in: query
                  required: true
                  schema:
                      type: string
                - name: year
                  in: query
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Transactions retrieved
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Transaction'
                '401':
                    description: Invalid or expired token
                '404':
                    description: No transactions found
                '500':
                    description: Server error

    /transactions/{transactionId}:
        get:
            summary: Get transaction details
            security:
                - bearerAuth: []
            parameters:
                - name: transactionId
                  in: path
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Transaction retrieved
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transaction'
                '401':
                    description: Invalid or expired token
                '404':
                    description: Transaction not found
                '500':
                    description: Server error
        patch:
            summary: Update metadata for a transaction (category, note)
            security:
                - bearerAuth: []
            parameters:
                - name: transactionId
                  in: path
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                category:
                                    type: string
                                    nullable: true
                                    description: New category; send empty string or null to clear
                                note:
                                    type: string
                                    nullable: true
                                    description: New note; send empty string or null to clear
                            additionalProperties: false
            responses:
                '200':
                    description: Transaction metadata updated
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Transaction'
                '400':
                    description: Invalid data
                '401':
                    description: Invalid or expired token
                '404':
                    description: Transaction not found
                '500':
                    description: Server error

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

    schemas:
        Account:
            type: object
            properties:
                accountId:
                    type: string
                name:
                    type: string
                balance:
                    type: number
                    format: double
            required: [accountId, name, balance]

        Transaction:
            type: object
            properties:
                transactionId:
                    type: string
                accountId:
                    type: string
                date:
                    type: string
                    format: date-time
                description:
                    type: string
                amount:
                    type: number
                    format: double
                transactionType:
                    type: string
                category:
                    type: string
                    nullable: true
                note:
                    type: string
                    nullable: true
            required:
                - transactionId
                - accountId
                - date
                - description
                - amount
                - transactionType
